# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='favorite', to='quotes.User'),
        ),
    ]
